# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path .bundle

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      - run:
          name: install unity
          command: |
            bundle exec rake u3d_install
          environment:
            # circleci is sudo passwordless. We still need to tell u3d.
            # you might need to hide from the config if you have different environment
            U3D_PASSWORD: ""
      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rake

      # collect reports
      - store_test_results:
          path: /tmp/rspec/
      - store_artifacts:
          path: /tmp/rspec/
          destination: test-results